name: Update gym graph
on:
  schedule:
    - cron: "0 3 * * *"   # täglich 03:00 UTC
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install requests
      - name: Generate SVG
        env:
          SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
        run: python scripts/gym_heatmap.py
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gym-graph.svg
          git commit -m "Update gym-graph.svg" || echo "No changes"
          git push
